const header = (value) => ({ value, label: value, edit: false });

const headers = (...values) => values.map(header);

const collection = (name, label, headerValues) => ({
  name,
  label,
  headers: headers(...headerValues),
});

const COLLECTIONS = [
  collection('patients', 'Patients', [
    'Id',
    'BIRTHDATE',
    'DEATHDATE',
    'SSN',
    'DRIVERS',
    'PASSPORT',
    'PREFIX',
    'FIRST',
    'LAST',
    'SUFFIX',
    'MAIDEN',
    'MARITAL',
    'RACE',
    'ETHNICITY',
    'GENDER',
    'BIRTHPLACE',
    'ADDRESS',
    'CITY',
    'STATE',
    'COUNTY',
    'ZIP',
    'LAT',
    'LON',
    'HEALTHCARE_EXPENSES',
    'HEALTHCARE_COVERAGE',
  ]),
  collection('allergies', 'Allergies', [
    'START',
    'STOP',
    'PATIENT',
    'ENCOUNTER',
    'CODE',
    'DESCRIPTION',
  ]),
  collection('careplans', 'Careplans', [
    'Id',
    'START',
    'STOP',
    'PATIENT',
    'ENCOUNTER',
    'CODE',
    'DESCRIPTION',
    'REASONCODE',
    'REASONDESCRIPTION',
  ]),
  collection('conditions', 'Conditions', [
    'START',
    'STOP',
    'PATIENT',
    'ENCOUNTER',
    'CODE',
    'DESCRIPTION',
  ]),
  collection('devices', 'Devices', [
    'START',
    'STOP',
    'PATIENT',
    'ENCOUNTER',
    'CODE',
    'DESCRIPTION',
    'UDI',
  ]),
  collection('encounters', 'Encounters', [
    'Id',
    'START',
    'STOP',
    'PATIENT',
    'ORGANIZATION',
    'PROVIDER',
    'PAYER',
    'ENCOUNTERCLASS',
    'CODE',
    'DESCRIPTION',
    'BASE_ENCOUNTER_COST',
    'TOTAL_CLAIM_COST',
    'PAYER_COVERAGE',
    'REASONCODE',
    'REASONDESCRIPTION',
  ]),
  collection('imaging_studies', 'Imaging Studies', [
    'Id',
    'DATE',
    'PATIENT',
    'ENCOUNTER',
    'BODYSITE_CODE',
    'BODYSITE_DESCRIPTION',
    'MODALITY_CODE',
    'MODALITY_DESCRIPTION',
    'SOP_CODE',
    'SOP_DESCRIPTION',
  ]),
  collection('immunizations', 'Immunizations', [
    'DATE',
    'PATIENT',
    'ENCOUNTER',
    'CODE',
    'DESCRIPTION',
    'BASE_COST',
  ]),
  collection('medications', 'Medications', [
    'START',
    'STOP',
    'PATIENT',
    'PAYER',
    'ENCOUNTER',
    'CODE',
    'DESCRIPTION',
    'BASE_COST',
    'PAYER_COVERAGE',
    'DISPENSES',
    'TOTALCOST',
    'REASONCODE',
    'REASONDESCRIPTION',
  ]),
  collection('observations', 'Observations', [
    'DATE',
    'PATIENT',
    'ENCOUNTER',
    'CODE',
    'DESCRIPTION',
    'VALUE',
    'UNITS',
    'TYPE',
  ]),
  collection('organizations', 'Organizations', [
    'Id',
    'NAME',
    'ADDRESS',
    'CITY',
    'STATE',
    'ZIP',
    'LAT',
    'LON',
    'PHONE',
    'REVENUE',
    'UTILIZATION',
  ]),
  collection('payer_transitions', 'Payer Transitions', [
    'PATIENT',
    'START_YEAR',
    'END_YEAR',
    'PAYER',
    'OWNERSHIP',
  ]),
  collection('payers', 'Payers', [
    'Id',
    'NAME',
    'ADDRESS',
    'CITY',
    'STATE_HEADQUARTERED',
    'ZIP',
    'PHONE',
    'AMOUNT_COVERED',
    'AMOUNT_UNCOVERED',
    'REVENUE',
    'COVERED_ENCOUNTERS',
    'UNCOVERED_ENCOUNTERS',
    'COVERED_MEDICATIONS',
    'UNCOVERED_MEDICATIONS',
    'COVERED_PROCEDURES',
    'UNCOVERED_PROCEDURES',
    'COVERED_IMMUNIZATIONS',
    'UNCOVERED_IMMUNIZATIONS',
    'UNIQUE_CUSTOMERS',
    'QOLS_AVG',
    'MEMBER_MONTHS',
  ]),
  collection('procedures', 'Procedures', [
    'DATE',
    'PATIENT',
    'ENCOUNTER',
    'CODE',
    'DESCRIPTION',
    'BASE_COST',
    'REASONCODE',
    'REASONDESCRIPTION',
  ]),
  collection('providers', 'Providers', [
    'Id',
    'ORGANIZATION',
    'NAME',
    'GENDER',
    'SPECIALITY',
    'ADDRESS',
    'CITY',
    'STATE',
    'ZIP',
    'LAT',
    'LON',
    'UTILIZATION',
  ]),
  collection('supplies', 'Supplies', [
    'DATE',
    'PATIENT',
    'ENCOUNTER',
    'CODE',
    'DESCRIPTION',
    'QUANTITY',
  ]),
];

const COLLECTION_CONFIG = Object.fromEntries(
  COLLECTIONS.map((collectionConfig) => [collectionConfig.name, collectionConfig]),
);

const DEFAULT_COLLECTION_CONFIG = {
  headers: [
    { value: 'id', label: 'id' },
    { value: 'resource', label: 'resource' },
  ],
};

export { COLLECTIONS, COLLECTION_CONFIG, DEFAULT_COLLECTION_CONFIG };
