module.exports = {
  ALLERGIES: 'allergies',
  CAREPLANS: 'careplans',
  CONDITIONS: 'conditions',
  DEVICES: 'devices',
  ENCOUNTERS: 'encounters',
  IMAGING_STUDIES: 'imaging_studies',
  IMMUNIZATIONS: 'immunizations',
  MEDICATIONS: 'medications',
  OBSERVATIONS: 'observations',
  ORGANIZATIONS: 'organizations',
  PATIENTS: 'patients',
  PAYER_TRANSITIONS: 'payer_transitions',
  PAYERS: 'payers',
  PROCEDURES: 'procedures',
  PROVIDERS: 'providers',
  SUPPLIES: 'supplies',
};
