on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - run: npm install

      - name: Run Build
        run: npm run build
        env:
          SYNTHETICMASS_API_KEY: ${{ secrets.SYNTHETICMASS_API_KEY }}

      - run: |
           mv public/index.html public/index.bak 
           sed -e 's/\/public/./g' public/index.bak > public/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.